spring:
  application:
    name: exp

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-circular-references: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000